# Generated by Django 5.1.7 on 2025-03-16 00:48

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('callboard', '0003_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='advertisment',
            options={'ordering': ['-created_at']},
        ),
        migrations.AddField(
            model_name='advertisment',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
        migrations.AlterField(
            model_name='advertisment',
            name='status',
            field=models.CharField(choices=[('pending', 'Заявок нет'), ('accepted', 'Принято'), ('rejected', 'отклонено')], default='pending', max_length=10),
        ),
        migrations.AlterField(
            model_name='comments',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
