# Generated by Django 5.1.7 on 2025-03-16 00:59

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('callboard', '0004_alter_advertisment_options_advertisment_created_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='advertisment',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2025, 3, 16, 0, 59, 53, 101144)),
        ),
    ]
