# Generated by Django 5.1.7 on 2025-03-16 09:24

import datetime
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('callboard', '0006_category_alter_advertisment_created_at_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='advertisment',
            name='category',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='callboard.category'),
        ),
        migrations.AlterField(
            model_name='advertisment',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2025, 3, 16, 9, 24, 32, 529067)),
        ),
        migrations.AlterField(
            model_name='advertisment',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
