# Generated by Django 5.1.7 on 2025-03-16 09:25

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('callboard', '0007_alter_advertisment_category_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='advertisment',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2025, 3, 16, 9, 25, 46, 563904)),
        ),
    ]
