# Generated by Django 5.1.7 on 2025-03-16 09:41

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('callboard', '0009_alter_advertisment_created_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='advertisment',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2025, 3, 16, 9, 41, 7, 602592)),
        ),
    ]
