# Generated by Django 5.1.7 on 2025-03-18 05:06

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('callboard', '0013_alter_advertisment_created_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='advertisment',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2025, 3, 18, 5, 6, 36, 390757)),
        ),
        migrations.AlterField(
            model_name='advertisment',
            name='status',
            field=models.CharField(choices=[('pending', 'Заявок нет'), ('accepted', 'Принято'), ('rejected', 'отклонено')], default='pending', max_length=50),
        ),
    ]
