version: '3.9'

services:
  web:
    build: .
    ports:
      - "8000:8000"
    volumes:
      - .:/terabit_test
    depends_on:
      - db
    environment:
      - DJANGO_SETTINGS_MODULE=terabit_test.settings
    env_file:
      - .env 

  db:
    image: postgres:15
    environment:
      POSTGRES_DB: ${DB_NAME}  
      POSTGRES_USER: ${DB_USER} 
      POSTGRES_PASSWORD: ${DB_PASSWORD}  
    ports:
      - "543:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
      - ./db-init:/docker-entrypoint-initdb.d

volumes:
  pgdata:
